version: "3.5"
services:
  server:
    image: hong:server 
    container_name: server
    ports:
      - "5000:3030"
    networks:
      - backend
  nginx:
    image: hong:nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend
  client:
    image: hong:client
    contianer_name: client
    ports: "3000:3000"
    networks:
      - backend

networks: # basic bridge network
  backend:
    driver: bridge
