version: "3.5"
services:
  server:
    image: chajyn/hong:server 
    container_name: server
    volumes:
      - /home/hong/.env:/usr/src/.env
    ports:
      - "5000:3030"
    networks:
      - backend
  nginx:
    image: chajyn/hong:nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend

networks: # basic bridge network
  backend:
    driver: bridge
