version: "3"
services:
  server:
    image: chajyn/hong:server 
    container_name: server
    volumes:
      - /home/hong/server2/.env:/usr/src/server.env
    ports:
      - "5000:3030"
    networks:
      - backend
  nginx:
    image: chajyn/hong:nginx
    links:
      - server
    volumes: /home/hong/nginx/public:/usr/share/nginx/public
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend

networks: # basic bridge network
  backend:
    driver: bridge
