version: "3.5"
services:
  server:
    image: chajyn/hong:server2 
    container_name: server
    ports:
      - "5000:3030"
    networks:
      - backend
  nginx:
    image: chajyn/hong:react-server2
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - backend

networks: # basic bridge network
  backend:
    driver: bridge
