version: "3.5"
services:
  server:
    container_name: server
    build: .
    ports:
      - "5000:3030"
    networks:
      - backend
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - backend

networks: # basic bridge network
  backend:
    driver: bridge
